default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        exclude: >
          (?x)^(
            (.*)/.pre-commit-config.yaml|
            (.*)/.github/workflows/release-please.yaml
          )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .markdownlint.yaml
          - --fix

  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]

  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        exclude: '^(.*)/tests/test_version.py'


  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: poetry run pytest tests/
        language: system
        pass_filenames: false
        verbose: true
